### ISSUE TITLE
Inserting data.

### ISSUE THREAD

**Issue by troyam** [Lure-of-Lysergide/mlp-generator#3]
Hi, first I want to say thanks for you project and I’ll help you to improve that.
I spend my time trying to understand how your architecture works and I decided asking you about some questions.

1- about data insert: we have a testNetwork function and I didn’t understand what’s the functionality about that.
2- when I created a data model I tried to train with some data, like a math problems without sucess.
3- how do you insert data to train?

**Comment by scifier** [comment]
Hello. Sorry about delay. I noticed just today this issue, cause I was involved in many projects and was unsubscribed from this project updates. I had some plans for this project, but currently I don't have enough time.

Currently, the only supported dataset is spambase. If you want to use another dataset you will need to rewrite the db middleware and a big part of network controller. I was a novice when I worked on this project and I understand that it must be refactored. So, the better solution it's to use your own fork of this project.
